// Global Map Variable
let tacticalMap = null;
let marker = null;

// Initialize Map on Load
document.addEventListener('DOMContentLoaded', () => {
    initMap(0, 0, 1); // Default center
});

function initMap(lat, lon, zoomLevel) {
    if (!tacticalMap) {
        tacticalMap = L.map('map', {
            zoomControl: false,
            attributionControl: false
        }).setView([lat, lon], zoomLevel);

        // Cyber-themed map tiles (using CartoDB Dark Matter as a base, CSS inverts/filters it)
        L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
            maxZoom: 19
        }).addTo(tacticalMap);

        // Custom cyber marker
        const cyberIcon = L.divIcon({
            className: 'cyber-marker',
            html: '<div style="color: var(--danger-color); font-size: 24px; text-shadow: 0 0 10px var(--danger-color);"><i class="fa-solid fa-crosshairs fa-spin-pulse"></i></div>',
            iconSize: [24, 24],
            iconAnchor: [12, 12]
        });

        marker = L.marker([lat, lon], { icon: cyberIcon }).addTo(tacticalMap);
    } else {
        tacticalMap.setView([lat, lon], zoomLevel);
        marker.setLatLng([lat, lon]);
    }
}

// Elements
const ipInput = document.getElementById('ipInput');
const scanBtn = document.getElementById('scanBtn');
const exportBtn = document.getElementById('exportBtn');
const loadingIndicator = document.getElementById('loadingIndicator');
const errorMessage = document.getElementById('errorMessage');
const resultsSection = document.getElementById('resultsSection');

// Event Listeners
scanBtn.addEventListener('click', handleScan);
ipInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') handleScan();
});

exportBtn.addEventListener('click', () => {
    const ip = document.getElementById('resIp').innerText || 'unknown';
    
    let report = `====================================================\n`;
    report += `      CYBERLOCATOR INTELLIGENCE REPORT\n`;
    report += `====================================================\n\n`;
    
    report += `[ TARGET IP ]: ${ip}\n`;
    report += `[ DATE ]: ${new Date().toLocaleString()}\n\n`;
    
    report += `--- GEOLOCATION DATA ---\n`;
    report += `Country: ${document.getElementById('resCountry').innerText}\n`;
    report += `Region/State: ${document.getElementById('resRegion').innerText}\n`;
    report += `City: ${document.getElementById('resCity').innerText}\n`;
    report += `Zip Code: ${document.getElementById('resZip').innerText}\n`;
    report += `Coordinates: ${document.getElementById('resCoords').innerText}\n`;
    report += `Timezone: ${document.getElementById('resTimezone').innerText}\n\n`;
    
    report += `--- NETWORK IDENTITY ---\n`;
    report += `ISP: ${document.getElementById('resIsp').innerText}\n`;
    report += `Organization: ${document.getElementById('resOrg').innerText}\n`;
    report += `ASN: ${document.getElementById('resAsn').innerText}\n`;
    report += `AS Name: ${document.getElementById('resAsName').innerText}\n`;
    report += `Connection Type: ${document.getElementById('resMobile').innerText}\n\n`;
    
    report += `--- THREAT INTELLIGENCE ---\n`;
    report += `Threat Level: ${document.getElementById('vpnStatusBanner').innerText.trim()}\n`;
    report += `Analyst Note: ${document.getElementById('aiAnalysisText').innerText.replace(/\n/g, ' ')}\n\n`;
    
    report += `--- WHOIS REGISTRATION DATA ---\n`;
    report += `${document.getElementById('whoisContent').innerText}\n\n`;
    
    report += `--- NETWORK PATH ANALYZER (MTR) ---\n`;
    report += `${document.getElementById('tracerouteContent').innerText}\n\n`;
    
    report += `====================================================\n`;
    report += `         Generated by CyberLocator Tool\n`;
    report += `====================================================\n`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CyberLocator_Report_${ip}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
});

async function handleScan() {
    let ip = ipInput.value.trim();
    
    // Auto-fill client IP if empty for demonstration
    if (!ip) {
        try {
            const res = await fetch('https://api.ipify.org?format=json');
            const data = await res.json();
            ip = data.ip;
            ipInput.value = ip;
        } catch (e) {
            showError("Please enter a valid IP address.");
            return;
        }
    }

    // Basic IP validation
    const ipRegex = /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$|^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$/;
    
    if (!ipRegex.test(ip)) {
        showError("Invalid IP Address format detected.");
        return;
    }

    // UI Updates
    hideError();
    resultsSection.classList.add('hidden');
    loadingIndicator.classList.remove('hidden');

    try {
        // We use ip-api.com over HTTP if possible to get proxy/hosting flags for free
        // Or we use ipapi.co as a fallback
        let url = `http://ip-api.com/json/${ip}?fields=status,message,country,regionName,city,zip,lat,lon,timezone,isp,org,as,asname,mobile,proxy,hosting,query`;
        
        // Check if we are on HTTPS, if so, we must use an HTTPS API (which might lack proxy flags for free)
        if (window.location.protocol === 'https:') {
            url = `https://ipapi.co/${ip}/json/`;
        }

        const response = await fetch(url);
        const data = await response.json();

        if (data.status === 'fail' || data.error) {
            throw new Error(data.message || data.reason || "Target unresolvable.");
        }

        populateData(data, ip);
        loadingIndicator.classList.add('hidden');
        resultsSection.classList.remove('hidden');
        exportBtn.classList.remove('hidden');
        
        // Update Map
        const lat = data.lat || data.latitude;
        const lon = data.lon || data.longitude;
        if (lat && lon) {
            setTimeout(() => {
                tacticalMap.invalidateSize();
                initMap(lat, lon, 12);
            }, 300);
        }

    } catch (error) {
        loadingIndicator.classList.add('hidden');
        showError(`Scan Failed: ${error.message}`);
    }
}

function populateData(data, ip) {
    // Determine which API format we got
    const isIpApi = data.query !== undefined;

    // Geo
    document.getElementById('resIp').innerText = isIpApi ? data.query : data.ip;
    document.getElementById('resCountry').innerText = isIpApi ? data.country : data.country_name;
    document.getElementById('resRegion').innerText = isIpApi ? data.regionName : data.region;
    document.getElementById('resCity').innerText = isIpApi ? data.city : data.city;
    document.getElementById('resZip').innerText = (isIpApi ? data.zip : data.postal) || "N/A";
    
    const lat = isIpApi ? data.lat : data.latitude;
    const lon = isIpApi ? data.lon : data.longitude;
    document.getElementById('resCoords').innerText = `${lat}, ${lon}`;
    document.getElementById('resTimezone').innerText = isIpApi ? data.timezone : data.timezone;

    // Network
    document.getElementById('resIsp').innerText = (isIpApi ? data.isp : data.org) || "Unknown";
    document.getElementById('resOrg').innerText = isIpApi ? data.org : "N/A";
    document.getElementById('resAsn').innerText = (isIpApi ? data.as : data.asn) || "Unknown";
    document.getElementById('resAsName').innerText = isIpApi ? data.asname : "N/A";
    document.getElementById('resMobile').innerText = isIpApi ? (data.mobile ? "Mobile Network" : "Broadband/Cable") : "Unknown";

    // Threat Intel
    let isProxy = false;
    let isHosting = false;

    if (isIpApi) {
        isProxy = data.proxy === true;
        isHosting = data.hosting === true;
    } else {
        // Heuristic fallback for ipapi.co (datacenter ASNs often indicate proxy/VPN)
        const asnString = (data.asn || "").toUpperCase();
        const orgString = (data.org || "").toUpperCase();
        const suspiciousKeywords = ['VPN', 'PROXY', 'HOSTING', 'DATACENTER', 'CLOUD', 'AWS', 'AMAZON', 'DIGITALOCEAN', 'HETZNER', 'LINODE', 'OVH', 'CHOOPA', 'M247'];
        
        if (suspiciousKeywords.some(kw => orgString.includes(kw))) {
            isProxy = true;
            isHosting = true;
        }
    }

    const resProxy = document.getElementById('resProxy');
    const resHosting = document.getElementById('resHosting');
    const vpnStatusBanner = document.getElementById('vpnStatusBanner');
    const resRisk = document.getElementById('resRisk');
    const aiAnalysisText = document.getElementById('aiAnalysisText');

    if (isProxy) {
        resProxy.innerHTML = 'TRUE <i class="fa-solid fa-triangle-exclamation"></i>';
        resProxy.className = 'value badge danger';
    } else {
        resProxy.innerText = 'FALSE';
        resProxy.className = 'value badge safe';
    }

    if (isHosting) {
        resHosting.innerText = 'TRUE';
        resHosting.className = 'value badge danger';
    } else {
        resHosting.innerText = 'FALSE';
        resHosting.className = 'value badge safe';
    }

    // Risk Assessment
    if (isProxy || isHosting) {
        vpnStatusBanner.innerHTML = '<i class="fa-solid fa-user-ninja"></i> Anonymization Detected';
        vpnStatusBanner.className = 'status-banner danger';
        resRisk.innerText = 'HIGH';
        resRisk.className = 'value risk-score high';
        
        let analysis = `Subject IP is routing through a commercial Datacenter/VPN node (${data.isp || data.org}). The true geographical location of the suspect is masked. `;
        analysis += `However, analyzing the timezone (${data.timezone}) and coordinating with ISP logs for ASN ${isIpApi ? data.as : data.asn} can reveal the originating packet source. Submit a lawful interception request to the ISP.`;
        aiAnalysisText.innerText = analysis;
    } else {
        vpnStatusBanner.innerHTML = '<i class="fa-solid fa-circle-check"></i> Clean Residential IP';
        vpnStatusBanner.className = 'status-banner';
        resRisk.innerText = 'LOW';
        resRisk.className = 'value risk-score low';

        aiAnalysisText.innerText = `IP belongs to a standard residential/mobile ISP (${data.isp || data.org}). The geolocation provided (Radius: ~5-10km around ${data.city}) is highly likely to be the physical location of the subject. Proceed with local law enforcement coordination.`;
    }

    // OSINT & Blacklist Update
    const currentIp = isIpApi ? data.query : data.ip;
    
    // Update OSINT Links
    document.getElementById('btnAbuseIPDB').href = `https://www.abuseipdb.com/check/${currentIp}`;
    document.getElementById('btnVirusTotal').href = `https://www.virustotal.com/gui/ip-address/${currentIp}`;
    document.getElementById('btnScamalytics').href = `https://scamalytics.com/ip/${currentIp}`;
    document.getElementById('btnShodan').href = `https://www.shodan.io/host/${currentIp}`;
    document.getElementById('btnCensys').href = `https://search.censys.io/hosts/${currentIp}`;

    // Simulate heuristic-based Abuse Score (since we don't have a live API key)
    const resAbuse = document.getElementById('resAbuse');
    const resVt = document.getElementById('resVt');
    
    if (isProxy || isHosting) {
        resAbuse.innerHTML = '<span style="color: var(--danger-color); font-weight: bold;">High Probability (Needs manual check)</span>';
        resVt.innerText = 'Possible hits on hosting IP';
    } else {
        resAbuse.innerHTML = '<span style="color: var(--primary-color);">Likely Clean (0% confidence)</span>';
        resVt.innerText = '0/94 security vendors';
    }

    // Traceroute Update
    const tracerouteContent = document.getElementById('tracerouteContent');
    tracerouteContent.innerHTML = 'Initiating traceroute to ' + currentIp + '...\nThis may take 10-20 seconds... <i class="fa-solid fa-spinner fa-spin"></i>';
    
    // We use our local Python backend to run a real traceroute
    fetch(`/api/traceroute?ip=${currentIp}`)
        .then(response => {
            if (response.ok) return response.json();
            throw new Error('Network response was not ok.');
        })
        .then(data => {
            if(data.contents) {
                // Remove some clutter from HackerTarget output if needed
                tracerouteContent.innerText = data.contents;
            } else {
                tracerouteContent.innerText = "Traceroute failed or blocked by gateway.";
            }
        })
        .catch(error => {
            tracerouteContent.innerText = "Error executing traceroute: " + error.message;
        });

    // WHOIS Lookup Update
    const whoisContent = document.getElementById('whoisContent');
    whoisContent.innerHTML = 'Connecting to IANA WHOIS Database...\nFetching registration data... <i class="fa-solid fa-spinner fa-spin"></i>';
    
    fetch(`/api/whois?ip=${currentIp}`)
        .then(response => {
            if (response.ok) return response.json();
            throw new Error('Network response was not ok.');
        })
        .then(data => {
            if(data.success && data.data) {
                whoisContent.innerText = data.data.trim();
            } else {
                whoisContent.innerText = "Failed to retrieve WHOIS data: " + (data.error || "Unknown error");
            }
        })
        .catch(error => {
            whoisContent.innerText = "Error executing WHOIS lookup: " + error.message;
        });
}

function showError(msg) {
    errorMessage.innerText = msg;
    errorMessage.classList.remove('hidden');
}

function hideError() {
    errorMessage.classList.add('hidden');
    errorMessage.innerText = "";
}
